#!/usr/bin/env bash

if command -v eza > /dev/null; then
    alias ls="eza --icons=auto --group-directories-first"
fi

alias lt="ls --tree"
alias la="ls -la"
alias lat="ls -la --tree"
alias ll="ls -l"
alias llt="ls -l --tree"
