#!/usr/bin/env bash
_fzf_complete_pass() {
  FZF_COMPLETION_TRIGGER='' _fzf_complete +m -- "$@" < <(
    local prefix
    prefix="${PASSWORD_STORE_DIR:-$HOME/.password-store}"
    command find -L "$prefix" \
      -name "*.gpg" -type f \
      | sed -e "s#${prefix}/\{0,1\}##" -e 's#\.gpg##' -e 's#\\#\\\\#' | sort
  )
}
[ -n "$BASH" ] && complete -F _fzf_complete_pass -o default -o bashdefault pass